from __future__ import annotations

"""Balanced item catalog. Keep each shop category at or below ten items.

Combat gear contributes modest flat stats; permanent consumable bonuses are small
and benefit from the existing soft caps. One-shot breakthrough/tribulation items
must be used through the breakthrough UI.
"""

EQUIP_SLOTS = ("weapon", "artifact", "armor", "accessory")

ITEMS: dict[str, dict] = {'tu_khi_dan': {'category': 'Đan dược',
                'name': 'Tụ Khí Đan',
                'rarity': 'Phàm',
                'type': 'consumable',
                'price': 1000,
                'marketable': True,
                'cultivation': 180,
                'description': 'Đan dược nhập môn, bổ sung linh khí.'},
 'hoi_khi_dan': {'category': 'Đan dược',
                 'name': 'Hồi Khí Đan',
                 'rarity': 'Phàm',
                 'type': 'consumable',
                 'price': 2000,
                 'marketable': True,
                 'cultivation': 350,
                 'description': 'Hồi phục linh khí, tăng tu vi.'},
 'hoi_huyet_dan': {'category': 'Đan dược',
                   'name': 'Hồi Huyết Đan',
                   'rarity': 'Hoàng',
                   'type': 'consumable',
                   'price': 3500,
                   'marketable': True,
                   'heal': 60,
                   'description': 'Hồi phục khí huyết trong và ngoài chiến đấu.'},
 'tru_co_dan': {'category': 'Đan dược',
                'name': 'Trúc Cơ Đan',
                'rarity': 'Huyền',
                'type': 'consumable',
                'price': 15000,
                'marketable': True,
                'breakthrough_bonus': 0.05,
                'description': 'Đạo đan dùng trong giao diện .dotpha, cộng 5% tỷ lệ đột phá cho lần thử.'},
 'kim_dan_dai_duoc': {'category': 'Đan dược',
                      'name': 'Kim Đan Đại Dược',
                      'rarity': 'Địa',
                      'type': 'consumable',
                      'price': 50000,
                      'marketable': True,
                      'breakthrough_bonus': 0.08,
                      'description': 'Đại dược dùng trong giao diện .dotpha, cộng 8% tỷ lệ đột phá cho lần thử.'},
 'loi_kiep_dan': {'category': 'Đan dược',
                  'name': 'Lôi Kiếp Đan',
                  'rarity': 'Địa',
                  'type': 'consumable',
                  'price': 42000,
                  'marketable': True,
                  'thunder_resistance': 0.12,
                  'description': 'Uống trước khi đột phá, giảm 12% sát thương Cửu Lôi Kiếp trong lần hộ '
                                 'kiếp kế tiếp.'},
 'liet_hoa_phu': {'category': 'Bùa chú',
                  'name': 'Liệt Hỏa Phù',
                  'rarity': 'Huyền',
                  'type': 'consumable',
                  'price': 12000,
                  'marketable': True,
                  'cultivation': 350,
                  'insight': 1,
                  'description': 'Hỏa lực tôi luyện ngộ tính.'},
 'bang_tam_phu': {'category': 'Bùa chú',
                  'name': 'Băng Tâm Phù',
                  'rarity': 'Huyền',
                  'type': 'consumable',
                  'price': 18000,
                  'marketable': True,
                  'cultivation': 400,
                  'mind': 1,
                  'description': 'Giữ tâm tĩnh, tăng đạo tâm.'},
 'cuu_loi_ho_than_phu': {'category': 'Bùa chú',
                         'name': 'Cửu Lôi Hộ Thân Phù',
                         'rarity': 'Địa',
                         'type': 'consumable',
                         'price': 32000,
                         'marketable': True,
                         'thunder_resistance': 0.1,
                         'description': 'Linh phù che chở thân thể, giảm 10% sát thương Cửu Lôi Kiếp '
                                        'trong lần hộ kiếp kế tiếp.'},
 'thanh_tam_ngoc_boi': {'category': 'Pháp bảo',
                        'name': 'Thanh Tâm Ngọc Bội',
                        'rarity': 'Hoàng',
                        'type': 'equipment',
                        'slot': 'artifact',
                        'attack': 4,
                        'defense': 12,
                        'price': 8000,
                        'marketable': True,
                        'description': 'Ngọc bội hộ tâm.'},
 'huyen_thiet_linh_kinh': {'category': 'Pháp bảo',
                           'name': 'Huyền Thiết Linh Kính',
                           'rarity': 'Huyền',
                           'type': 'equipment',
                           'slot': 'artifact',
                           'attack': 8,
                           'defense': 18,
                           'thunder_resistance': 0.05,
                           'price': 20000,
                           'marketable': True,
                           'description': 'Linh kính phản chiếu linh lực, giảm 5% sát thương Cửu Lôi '
                                          'Kiếp khi trang bị.'},
 'thien_loi_chau': {'category': 'Pháp bảo',
                    'name': 'Thiên Lôi Châu',
                    'rarity': 'Địa',
                    'type': 'equipment',
                    'slot': 'artifact',
                    'attack': 4,
                    'defense': 16,
                    'thunder_resistance': 0.08,
                    'price': 60000,
                    'marketable': True,
                    'description': 'Pháp bảo dẫn lôi nhập châu, giảm 8% sát thương Cửu Lôi Kiếp khi '
                                   'trang bị.'},
 'thien_kiem': {'category': 'Binh khí',
                'name': 'Thiên Kiếm',
                'rarity': 'Huyền',
                'type': 'equipment',
                'slot': 'weapon',
                'attack': 30,
                'defense': 3,
                'price': 30000,
                'marketable': True,
                'description': 'Kiếm sắc, hợp Kiếm Đạo.'},
 'huyen_thiet_dao': {'category': 'Binh khí',
                     'name': 'Huyền Thiết Đao',
                     'rarity': 'Huyền',
                     'type': 'equipment',
                     'slot': 'weapon',
                     'attack': 32,
                     'defense': 2,
                     'price': 30000,
                     'marketable': True,
                     'description': 'Đao nặng, hợp Đao Đạo.'},
 'kim_cang_giap': {'category': 'Pháp bảo',
                   'name': 'Kim Cang Giáp',
                   'rarity': 'Địa',
                   'type': 'equipment',
                   'slot': 'armor',
                   'attack': 3,
                   'defense': 32,
                   'price': 60000,
                   'marketable': True,
                   'description': 'Giáp cứng như kim cang.',
                   'max_hp': 20},
 'linh_ngoc_gioi': {'category': 'Pháp bảo',
                    'name': 'Linh Ngọc Giới',
                    'rarity': 'Hoàng',
                    'type': 'equipment',
                    'slot': 'accessory',
                    'attack': 4,
                    'defense': 6,
                    'price': 12000,
                    'marketable': True,
                    'description': 'Nhẫn ngọc tăng linh lực nhẹ.',
                    'max_hp': 10},
 'hon_don_dao_kinh': {'category': 'Công pháp',
                      'name': 'Hỗn Độn Đạo Kinh',
                      'rarity': 'Địa',
                      'type': 'technique',
                      'price': 100000,
                      'marketable': True,
                      'technique_stat': 'insight',
                      'technique_bonus': 2,
                      'skill_power': 1.25,
                      'description': 'Công pháp thượng thừa, tăng ngộ tính.'},
 'kiem_tam_quyet': {'category': 'Công pháp',
                    'name': 'Kiếm Tâm Quyết',
                    'rarity': 'Huyền',
                    'type': 'technique',
                    'price': 40000,
                    'marketable': True,
                    'technique_stat': 'root',
                    'technique_bonus': 1,
                    'skill_power': 1.18,
                    'description': 'Kiếm tâm vững, tăng căn cơ.'},
 'cuong_dao_quyet': {'category': 'Công pháp',
                     'name': 'Cuồng Đao Quyết',
                     'rarity': 'Huyền',
                     'type': 'technique',
                     'price': 40000,
                     'marketable': True,
                     'technique_stat': 'root',
                     'technique_bonus': 1,
                     'skill_power': 1.2,
                     'description': 'Đao ý cuồng bạo.'},
 'boom_heal_small': {'category': 'Đan dược',
                     'name': 'Tiểu Hồi Huyết Đan',
                     'rarity': 'Phàm',
                     'type': 'combat_item',
                     'price': 1500,
                     'marketable': True,
                     'heal': 40,
                     'description': 'Hồi 40 HP trong chiến đấu.'},
 'linh_tuy_dan': {'category': 'Đan dược',
                  'name': 'Linh Tủy Đan',
                  'rarity': 'Hoàng',
                  'type': 'consumable',
                  'price': 4500,
                  'marketable': True,
                  'cultivation': 650,
                  'root': 1,
                  'description': 'Bổ sung linh khí và cải thiện căn cơ một chút.'},
 'minh_tam_dan': {'category': 'Đan dược',
                  'name': 'Minh Tâm Đan',
                  'rarity': 'Hoàng',
                  'type': 'consumable',
                  'price': 5500,
                  'marketable': True,
                  'cultivation': 500,
                  'insight': 1,
                  'description': 'Tăng nhẹ tu vi và ngộ tính.'},
 'duong_huyet_dan': {'category': 'Đan dược',
                     'name': 'Dưỡng Huyết Đan',
                     'rarity': 'Hoàng',
                     'type': 'consumable',
                     'price': 4200,
                     'marketable': True,
                     'heal': 100,
                     'description': 'Hồi phục lượng HP vừa phải.'},
 'qing_moc_phu': {'category': 'Bùa chú',
                  'name': 'Thanh Mộc Phù',
                  'rarity': 'Phàm',
                  'type': 'consumable',
                  'price': 3000,
                  'marketable': True,
                  'cultivation': 300,
                  'root': 1,
                  'description': 'Linh phù ổn định căn cơ, tăng ít tu vi.'},
 'ngung_than_phu': {'category': 'Bùa chú',
                    'name': 'Ngưng Thần Phù',
                    'rarity': 'Hoàng',
                    'type': 'consumable',
                    'price': 6000,
                    'marketable': True,
                    'insight': 2,
                    'description': 'Tĩnh tâm ngưng thần, tăng nhẹ ngộ tính.'},
 'bo_nguyen_phu': {'category': 'Bùa chú',
                   'name': 'Bổ Nguyên Phù',
                   'rarity': 'Hoàng',
                   'type': 'consumable',
                   'price': 6500,
                   'marketable': True,
                   'cultivation': 700,
                   'description': 'Bổ sung một lượng tu vi vừa phải.'},
 'kien_tam_phu': {'category': 'Bùa chú',
                  'name': 'Kiên Tâm Phù',
                  'rarity': 'Hoàng',
                  'type': 'consumable',
                  'price': 6500,
                  'marketable': True,
                  'mind': 2,
                  'description': 'Củng cố đạo tâm, không tăng sức mạnh chiến đấu trực tiếp.'},
 'ho_mach_phu': {'category': 'Bùa chú',
                 'name': 'Hộ Mạch Phù',
                 'rarity': 'Huyền',
                 'type': 'consumable',
                 'price': 14000,
                 'marketable': True,
                 'breakthrough_bonus': 0.05,
                 'description': 'Tăng 5% tỷ lệ đột phá cho một lần, dùng qua giao diện .dotpha.'},
 'tinh_loi_phu': {'category': 'Bùa chú',
                  'name': 'Tĩnh Lôi Phù',
                  'rarity': 'Huyền',
                  'type': 'consumable',
                  'price': 18000,
                  'marketable': True,
                  'thunder_resistance': 0.08,
                  'description': 'Giảm 8% sát thương Cửu Lôi Kiếp trong lần hộ kiếp kế tiếp.'},
 'tran_tam_phu': {'category': 'Bùa chú',
                  'name': 'Trấn Tâm Phù',
                  'rarity': 'Hoàng',
                  'type': 'consumable',
                  'price': 5500,
                  'marketable': True,
                  'fate': 1,
                  'description': 'Giữ tâm cảnh ổn định, tăng nhẹ mệnh số.'},
 'bich_ngoc_ho_tam': {'category': 'Pháp bảo',
                      'name': 'Bích Ngọc Hộ Tâm',
                      'rarity': 'Hoàng',
                      'type': 'equipment',
                      'slot': 'artifact',
                      'attack': 2,
                      'defense': 10,
                      'max_hp': 8,
                      'price': 10000,
                      'marketable': True,
                      'description': 'Pháp bảo phòng hộ cơ bản, tăng nhẹ thủ và HP tối đa.'},
 'tinh_van_bao_kien': {'category': 'Pháp bảo',
                       'name': 'Tinh Vân Bảo Kiện',
                       'rarity': 'Huyền',
                       'type': 'equipment',
                       'slot': 'artifact',
                       'attack': 5,
                       'defense': 14,
                       'max_hp': 8,
                       'price': 26000,
                       'marketable': True,
                       'description': 'Bảo kiện cân bằng, không thiên lệch quá nhiều về một chỉ số.'},
 'thanh_linh_y': {'category': 'Pháp bảo',
                  'name': 'Thanh Linh Y',
                  'rarity': 'Hoàng',
                  'type': 'equipment',
                  'slot': 'armor',
                  'attack': 1,
                  'defense': 18,
                  'max_hp': 15,
                  'price': 18000,
                  'marketable': True,
                  'description': 'Áo linh nhẹ, tăng thủ và một ít HP tối đa.'},
 'huyen_vu_giap': {'category': 'Pháp bảo',
                   'name': 'Huyền Vũ Giáp',
                   'rarity': 'Huyền',
                   'type': 'equipment',
                   'slot': 'armor',
                   'attack': 0,
                   'defense': 28,
                   'max_hp': 22,
                   'price': 42000,
                   'marketable': True,
                   'description': 'Giáp nặng thiên về phòng thủ, không cộng công lớn.'},
 'tu_kim_gioi': {'category': 'Pháp bảo',
                 'name': 'Tử Kim Giới',
                 'rarity': 'Huyền',
                 'type': 'equipment',
                 'slot': 'accessory',
                 'attack': 5,
                 'defense': 5,
                 'max_hp': 8,
                 'price': 22000,
                 'marketable': True,
                 'description': 'Nhẫn cân bằng, tăng nhẹ ba chỉ số chiến đấu.'},
 'qing_feng_kiem': {'category': 'Binh khí',
                    'name': 'Thanh Phong Kiếm',
                    'rarity': 'Phàm',
                    'type': 'equipment',
                    'slot': 'weapon',
                    'attack': 12,
                    'defense': 1,
                    'price': 2500,
                    'marketable': True,
                    'description': 'Kiếm nhập môn, nhẹ và dễ sử dụng.'},
 'tinh_cuong_thuong': {'category': 'Binh khí',
                       'name': 'Tinh Cương Thương',
                       'rarity': 'Hoàng',
                       'type': 'equipment',
                       'slot': 'weapon',
                       'attack': 18,
                       'defense': 2,
                       'price': 8500,
                       'marketable': True,
                       'description': 'Thương bền bỉ, công kích ổn định.'},
 'liem_nguyet_dao': {'category': 'Binh khí',
                     'name': 'Liêm Nguyệt Đao',
                     'rarity': 'Hoàng',
                     'type': 'equipment',
                     'slot': 'weapon',
                     'attack': 20,
                     'defense': 1,
                     'price': 10000,
                     'marketable': True,
                     'description': 'Đao thiên công nhưng không có chỉ số quá cao.'},
 'bach_van_kiem': {'category': 'Binh khí',
                   'name': 'Bạch Vân Kiếm',
                   'rarity': 'Huyền',
                   'type': 'equipment',
                   'slot': 'weapon',
                   'attack': 25,
                   'defense': 2,
                   'price': 22000,
                   'marketable': True,
                   'description': 'Kiếm trung cấp, phù hợp giai đoạn Trúc Cơ.'},
 'ngu_hanh_quyet': {'category': 'Công pháp',
                    'name': 'Ngũ Hành Quyết',
                    'rarity': 'Phàm',
                    'type': 'technique',
                    'price': 8000,
                    'marketable': True,
                    'technique_stat': 'mind',
                    'technique_bonus': 1,
                    'skill_power': 1.1,
                    'description': 'Công pháp cơ bản, cân bằng đạo tâm và kỹ năng.'},
 'kim_chung_quyet': {'category': 'Công pháp',
                     'name': 'Kim Chung Quyết',
                     'rarity': 'Hoàng',
                     'type': 'technique',
                     'price': 18000,
                     'marketable': True,
                     'technique_stat': 'mind',
                     'technique_bonus': 1,
                     'skill_power': 1.13,
                     'description': 'Công pháp phòng ngự, hiệu quả ổn định.'},
 'van_moc_tam_kinh': {'category': 'Công pháp',
                      'name': 'Vạn Mộc Tâm Kinh',
                      'rarity': 'Huyền',
                      'type': 'technique',
                      'price': 28000,
                      'marketable': True,
                      'technique_stat': 'root',
                      'technique_bonus': 1,
                      'skill_power': 1.15,
                      'description': 'Tâm kinh nuôi dưỡng căn cơ, sức mạnh kỹ năng tăng nhẹ.'},
 'phi_tinh_kiem_phap': {'category': 'Công pháp',
                        'name': 'Phi Tinh Kiếm Pháp',
                        'rarity': 'Huyền',
                        'type': 'technique',
                        'price': 32000,
                        'marketable': True,
                        'technique_stat': 'insight',
                        'technique_bonus': 1,
                        'skill_power': 1.18,
                        'description': 'Kiếm pháp nhanh, yêu cầu người tu luyện lĩnh hội.'},
 'huyen_thuy_kinh': {'category': 'Công pháp',
                     'name': 'Huyền Thủy Kinh',
                     'rarity': 'Huyền',
                     'type': 'technique',
                     'price': 34000,
                     'marketable': True,
                     'technique_stat': 'fate',
                     'technique_bonus': 1,
                     'skill_power': 1.16,
                     'description': 'Tâm pháp ổn định, không tạo đột biến sát thương.'},
 'pha_quan_dao': {'category': 'Công pháp',
                  'name': 'Phá Quân Đạo',
                  'rarity': 'Địa',
                  'type': 'technique',
                  'price': 60000,
                  'marketable': True,
                  'technique_stat': 'root',
                  'technique_bonus': 2,
                  'skill_power': 1.22,
                  'description': 'Đao quyết cấp cao, thiên về công kích nhưng vẫn giữ mức tăng hợp lý.'},
 'liet_son_phu': {'category': 'Binh khí',
                  'name': 'Liệt Sơn Phủ',
                  'rarity': 'Huyền',
                  'type': 'equipment',
                  'slot': 'weapon',
                  'attack': 27,
                  'defense': 0,
                  'price': 24000,
                  'marketable': True,
                  'description': 'Rìu nặng có công cao hơn một chút, gần như không tăng thủ.'},
 'long_van_kiem': {'category': 'Binh khí',
                   'name': 'Long Vân Kiếm',
                   'rarity': 'Địa',
                   'type': 'equipment',
                   'slot': 'weapon',
                   'attack': 32,
                   'defense': 3,
                   'price': 48000,
                   'marketable': True,
                   'description': 'Danh kiếm cấp cao, chỉ tăng công ở mức vừa phải.'},
 'chan_vuong_thuong': {'category': 'Binh khí',
                       'name': 'Chấn Vương Thương',
                       'rarity': 'Địa',
                       'type': 'equipment',
                       'slot': 'weapon',
                       'attack': 34,
                       'defense': 2,
                       'price': 52000,
                       'marketable': True,
                       'description': 'Trường thương mạnh nhưng không vượt trội toàn diện.'},
 'thien_thanh_kiem': {'category': 'Binh khí',
                      'name': 'Thiên Thanh Kiếm',
                      'rarity': 'Thiên',
                      'type': 'equipment',
                      'slot': 'weapon',
                      'attack': 40,
                      'defense': 3,
                      'price': 90000,
                      'marketable': True,
                      'description': 'Bảo kiếm hiếm, dành cho người chơi giai đoạn cao.'},
 'linh_xa_bo': {'category': 'Công pháp',
                'name': 'Linh Xà Bộ',
                'rarity': 'Hoàng',
                'type': 'technique',
                'price': 16000,
                'marketable': True,
                'technique_stat': 'luck',
                'technique_bonus': 1,
                'skill_power': 1.12,
                'description': 'Thân pháp linh hoạt, tăng nhẹ may mắn và sức mạnh kỹ năng.'}}

SHOP_ORDER = ["Đan dược", "Bùa chú", "Pháp bảo", "Binh khí", "Công pháp"]
SHOP_CATEGORIES = {
    cat: [iid for iid, it in ITEMS.items() if it.get("category") == cat and it.get("price")]
    for cat in SHOP_ORDER
}


def item_slot(item_id: str) -> str | None:
    item = ITEMS.get(item_id) or {}
    return item.get("slot")
